import { useMutation, useQueryClient } from "@tanstack/react-query";
import axios from "axios";
import { useState } from "react";
import { toast } from "sonner";

import { fileService } from "@/lib/api/services/file-service";
import { FileItem } from "@/types/files";

import { fileExplorerKeys } from "./use-files";
import { userStatsKeys } from "./use-user";

export const useUpload = () => {
  const [progress, setProgress] = useState<number>(0);
  const [isUploading, setIsUploading] = useState(false);
  const queryClient = useQueryClient();

  const uploadMutation = useMutation<
    FileItem,
    { message: string },
    { file: File; folderId?: string | null }
  >({
    mutationFn: async ({ file, folderId }) => {
      setIsUploading(true);
      setProgress(0);

      try {
        // 1. Get Signed URL & Signature details from backend
        const authData = await fileService.getSignedUrl({
          fileName: file.name,
          fileType: file.type,
          fileSize: file.size,
          folderId,
        });

        // 2. Upload to Cloudinary using Form Data (Signed Upload)
        const formData = new FormData();
        formData.append("file", file);
        formData.append("api_key", authData.apiKey);
        formData.append("timestamp", authData.timestamp.toString());
        formData.append("signature", authData.signature);
        formData.append("public_id", authData.publicId);

        await axios.post(authData.uploadUrl, formData, {
          onUploadProgress: (progressEvent) => {
            const percentCompleted = Math.round(
              (progressEvent.loaded * 100) / (progressEvent.total || 1)
            );
            setProgress(percentCompleted);
          },
        });

        // 3. Confirm Upload with Backend
        const confirmedFile = await fileService.confirmUpload({
          name: file.name,
          size: file.size,
          mimeType: file.type,
          s3Key: authData.publicId, // Using the same public_id generated by backend
          folderId,
        });

        return confirmedFile;
      } catch (error: unknown) {
        const err = error as {
          response?: { data?: { error?: { message?: string } } };
          message?: string;
        };
        const message = err.response?.data?.error?.message || err.message || "Upload failed";
        throw new Error(message);
      } finally {
        setIsUploading(false);
      }
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: fileExplorerKeys.files(data.folderId) });
      queryClient.invalidateQueries({ queryKey: userStatsKeys.all });
      toast.success("File uploaded successfully");
      setProgress(0);
    },
    onError: (error) => {
      toast.error(error.message || "Failed to upload file");
      setProgress(0);
    },
  });

  return {
    ...uploadMutation,
    progress,
    isUploading,
  };
};
